// Generated by gencpp from file inverse_problem_srv/point_cmd.msg
// DO NOT EDIT!


#ifndef INVERSE_PROBLEM_SRV_MESSAGE_POINT_CMD_H
#define INVERSE_PROBLEM_SRV_MESSAGE_POINT_CMD_H

#include <ros/service_traits.h>


#include <inverse_problem_srv/point_cmdRequest.h>
#include <inverse_problem_srv/point_cmdResponse.h>


namespace inverse_problem_srv
{

struct point_cmd
{

typedef point_cmdRequest Request;
typedef point_cmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct point_cmd
} // namespace inverse_problem_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::inverse_problem_srv::point_cmd > {
  static const char* value()
  {
    return "fa0ec09bde95d41bf847bf7226201e41";
  }

  static const char* value(const ::inverse_problem_srv::point_cmd&) { return value(); }
};

template<>
struct DataType< ::inverse_problem_srv::point_cmd > {
  static const char* value()
  {
    return "inverse_problem_srv/point_cmd";
  }

  static const char* value(const ::inverse_problem_srv::point_cmd&) { return value(); }
};


// service_traits::MD5Sum< ::inverse_problem_srv::point_cmdRequest> should match
// service_traits::MD5Sum< ::inverse_problem_srv::point_cmd >
template<>
struct MD5Sum< ::inverse_problem_srv::point_cmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::inverse_problem_srv::point_cmd >::value();
  }
  static const char* value(const ::inverse_problem_srv::point_cmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::inverse_problem_srv::point_cmdRequest> should match
// service_traits::DataType< ::inverse_problem_srv::point_cmd >
template<>
struct DataType< ::inverse_problem_srv::point_cmdRequest>
{
  static const char* value()
  {
    return DataType< ::inverse_problem_srv::point_cmd >::value();
  }
  static const char* value(const ::inverse_problem_srv::point_cmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::inverse_problem_srv::point_cmdResponse> should match
// service_traits::MD5Sum< ::inverse_problem_srv::point_cmd >
template<>
struct MD5Sum< ::inverse_problem_srv::point_cmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::inverse_problem_srv::point_cmd >::value();
  }
  static const char* value(const ::inverse_problem_srv::point_cmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::inverse_problem_srv::point_cmdResponse> should match
// service_traits::DataType< ::inverse_problem_srv::point_cmd >
template<>
struct DataType< ::inverse_problem_srv::point_cmdResponse>
{
  static const char* value()
  {
    return DataType< ::inverse_problem_srv::point_cmd >::value();
  }
  static const char* value(const ::inverse_problem_srv::point_cmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INVERSE_PROBLEM_SRV_MESSAGE_POINT_CMD_H
