// Generated by gencpp from file inverse_problem_srv/publish_cmd.msg
// DO NOT EDIT!


#ifndef INVERSE_PROBLEM_SRV_MESSAGE_PUBLISH_CMD_H
#define INVERSE_PROBLEM_SRV_MESSAGE_PUBLISH_CMD_H

#include <ros/service_traits.h>


#include <inverse_problem_srv/publish_cmdRequest.h>
#include <inverse_problem_srv/publish_cmdResponse.h>


namespace inverse_problem_srv
{

struct publish_cmd
{

typedef publish_cmdRequest Request;
typedef publish_cmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct publish_cmd
} // namespace inverse_problem_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::inverse_problem_srv::publish_cmd > {
  static const char* value()
  {
    return "d6ac0cf017b131c2669cb2b0322255b3";
  }

  static const char* value(const ::inverse_problem_srv::publish_cmd&) { return value(); }
};

template<>
struct DataType< ::inverse_problem_srv::publish_cmd > {
  static const char* value()
  {
    return "inverse_problem_srv/publish_cmd";
  }

  static const char* value(const ::inverse_problem_srv::publish_cmd&) { return value(); }
};


// service_traits::MD5Sum< ::inverse_problem_srv::publish_cmdRequest> should match
// service_traits::MD5Sum< ::inverse_problem_srv::publish_cmd >
template<>
struct MD5Sum< ::inverse_problem_srv::publish_cmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::inverse_problem_srv::publish_cmd >::value();
  }
  static const char* value(const ::inverse_problem_srv::publish_cmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::inverse_problem_srv::publish_cmdRequest> should match
// service_traits::DataType< ::inverse_problem_srv::publish_cmd >
template<>
struct DataType< ::inverse_problem_srv::publish_cmdRequest>
{
  static const char* value()
  {
    return DataType< ::inverse_problem_srv::publish_cmd >::value();
  }
  static const char* value(const ::inverse_problem_srv::publish_cmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::inverse_problem_srv::publish_cmdResponse> should match
// service_traits::MD5Sum< ::inverse_problem_srv::publish_cmd >
template<>
struct MD5Sum< ::inverse_problem_srv::publish_cmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::inverse_problem_srv::publish_cmd >::value();
  }
  static const char* value(const ::inverse_problem_srv::publish_cmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::inverse_problem_srv::publish_cmdResponse> should match
// service_traits::DataType< ::inverse_problem_srv::publish_cmd >
template<>
struct DataType< ::inverse_problem_srv::publish_cmdResponse>
{
  static const char* value()
  {
    return DataType< ::inverse_problem_srv::publish_cmd >::value();
  }
  static const char* value(const ::inverse_problem_srv::publish_cmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INVERSE_PROBLEM_SRV_MESSAGE_PUBLISH_CMD_H
