// Generated by gencpp from file inverse_problem_srv/point_cmdRequest.msg
// DO NOT EDIT!


#ifndef INVERSE_PROBLEM_SRV_MESSAGE_POINT_CMDREQUEST_H
#define INVERSE_PROBLEM_SRV_MESSAGE_POINT_CMDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inverse_problem_srv
{
template <class ContainerAllocator>
struct point_cmdRequest_
{
  typedef point_cmdRequest_<ContainerAllocator> Type;

  point_cmdRequest_()
    : point()  {
    }
  point_cmdRequest_(const ContainerAllocator& _alloc)
    : point(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct point_cmdRequest_

typedef ::inverse_problem_srv::point_cmdRequest_<std::allocator<void> > point_cmdRequest;

typedef boost::shared_ptr< ::inverse_problem_srv::point_cmdRequest > point_cmdRequestPtr;
typedef boost::shared_ptr< ::inverse_problem_srv::point_cmdRequest const> point_cmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator1> & lhs, const ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator1> & lhs, const ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace inverse_problem_srv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ed1de399ba3b5ba9705fbb7770ebcef";
  }

  static const char* value(const ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ed1de399ba3b5baULL;
  static const uint64_t static_value2 = 0x9705fbb7770ebcefULL;
};

template<class ContainerAllocator>
struct DataType< ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inverse_problem_srv/point_cmdRequest";
  }

  static const char* value(const ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string point \n"
"\n"
;
  }

  static const char* value(const ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct point_cmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inverse_problem_srv::point_cmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "point: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INVERSE_PROBLEM_SRV_MESSAGE_POINT_CMDREQUEST_H
