// Generated by gencpp from file inverse_problem_srv/publish_cmdRequest.msg
// DO NOT EDIT!


#ifndef INVERSE_PROBLEM_SRV_MESSAGE_PUBLISH_CMDREQUEST_H
#define INVERSE_PROBLEM_SRV_MESSAGE_PUBLISH_CMDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inverse_problem_srv
{
template <class ContainerAllocator>
struct publish_cmdRequest_
{
  typedef publish_cmdRequest_<ContainerAllocator> Type;

  publish_cmdRequest_()
    : jointState()  {
    }
  publish_cmdRequest_(const ContainerAllocator& _alloc)
    : jointState(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _jointState_type;
  _jointState_type jointState;





  typedef boost::shared_ptr< ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct publish_cmdRequest_

typedef ::inverse_problem_srv::publish_cmdRequest_<std::allocator<void> > publish_cmdRequest;

typedef boost::shared_ptr< ::inverse_problem_srv::publish_cmdRequest > publish_cmdRequestPtr;
typedef boost::shared_ptr< ::inverse_problem_srv::publish_cmdRequest const> publish_cmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator1> & lhs, const ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.jointState == rhs.jointState;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator1> & lhs, const ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace inverse_problem_srv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ef9169302944380b1360b90aedc31a6";
  }

  static const char* value(const ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ef9169302944380ULL;
  static const uint64_t static_value2 = 0xb1360b90aedc31a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inverse_problem_srv/publish_cmdRequest";
  }

  static const char* value(const ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string jointState \n"
"\n"
;
  }

  static const char* value(const ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.jointState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct publish_cmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inverse_problem_srv::publish_cmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "jointState: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.jointState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INVERSE_PROBLEM_SRV_MESSAGE_PUBLISH_CMDREQUEST_H
